version: '3.4'

services: 
  stur:
    image: stur-image
    depends_on: 
      - "postgres-image"
    build: 
      context: ./src/STUR-mvc
      dockerfile: Dockerfile
    ports: 
      - "5100:80"

  postgres-image:
    image: postgres:latest
    ports: 
      - "5432"
    restart: always
    volumes: 
      - db_volume:/var/lib/postgresql/data
    environment: 
      POSTGRES_USER: "stur_user"
      POSTGRES_PASSWORD: "stur2021"
      POSTGRES_DB: "sturdb"

volumes: 
  db_volume: