version: "3.4"

services:  
  stur:
    image: stur-image
    build: 
      context: .
      dockerfile: Dockerfile
    ports: 
      - "6001:80"
    environment: 
      ASPNETCORE_ENVIRONMENT: Development            